apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.10.0
        args: ["-e", "-c", "/usr/share/filebeat/filebeat.yml"]
        securityContext:
          runAsUser: 0  # Set the user to 0 for root
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
        command: ["/usr/share/filebeat/docker-entrypoint.sh", "-e"]
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: filebeat-config
        configMap:
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
